#file: noinspection YAMLSchemaValidation
spring:
  application:
    name: Pagination

  datasource:
    url: jdbc:mysql://localhost:3306/${DB_NAME}?useSSL=false&serverTimezone=UTC
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight: true
  flyway:
    enabled: true
    locations: classpath:db/migrations
    baseline-on-migrate: true
server:
  port: 4004
  servlet:
    context-path: /api/v1

logging:
  level:
    root: info