INSERT INTO products (name, category, price, created_at)
VALUES
-- Electronics (20 products)
('iPhone 15 Pro', 'Electronics', 1299.99, NOW()),
('Samsung Galaxy S24', 'Electronics', 999.99, NOW()),
('Sony WH-1000XM5 Headphones', 'Electronics', 349.99, NOW()),
('Apple MacBook Air M3', 'Electronics', 1099.99, NOW()),
('Dell XPS 15 Laptop', 'Electronics', 1799.99, NOW()),
('iPad Pro 12.9', 'Electronics', 1099.99, NOW()),
('LG OLED 55" TV', 'Electronics', 1499.99, NOW()),
('Canon EOS R50 Camera', 'Electronics', 679.99, NOW()),
('Bose SoundLink Speaker', 'Electronics', 149.99, NOW()),
('Apple Watch Series 9', 'Electronics', 399.99, NOW()),
('Kindle Paperwhite', 'Electronics', 139.99, NOW()),
('GoPro Hero 12', 'Electronics', 399.99, NOW()),
('Nintendo Switch OLED', 'Electronics', 349.99, NOW()),
('PS5 Controller', 'Electronics', 69.99, NOW()),
('Logitech MX Master 3', 'Electronics', 99.99, NOW()),
('Samsung 27" Monitor', 'Electronics', 349.99, NOW()),
('Corsair Mechanical Keyboard', 'Electronics', 129.99, NOW()),
('JBL Earbuds Pro', 'Electronics', 179.99, NOW()),
('Anker 65W Charger', 'Electronics', 35.99, NOW()),
('TP-Link WiFi Router', 'Electronics', 89.99, NOW()),

-- Clothing (20 products)
('Nike Air Max 270', 'Clothing', 149.99, NOW()),
('Adidas Ultraboost 22', 'Clothing', 189.99, NOW()),
('Levi 501 Jeans', 'Clothing', 69.99, NOW()),
('North Face Winter Jacket', 'Clothing', 249.99, NOW()),
('Ralph Lauren Polo Shirt', 'Clothing', 89.99, NOW()),
('Zara Slim Fit Chinos', 'Clothing', 49.99, NOW()),
('H&M Cotton T-Shirt Pack', 'Clothing', 29.99, NOW()),
('Under Armour Hoodie', 'Clothing', 64.99, NOW()),
('Puma Track Pants', 'Clothing', 44.99, NOW()),
('Ray-Ban Aviator Sunglasses', 'Clothing', 154.99, NOW()),
('Timberland Boots', 'Clothing', 199.99, NOW()),
('Columbia Rain Jacket', 'Clothing', 139.99, NOW()),
('Champion Sweatshirt', 'Clothing', 54.99, NOW()),
('New Balance 990v5', 'Clothing', 174.99, NOW()),
('Tommy Hilfiger Belt', 'Clothing', 44.99, NOW()),
('Uniqlo Fleece Jacket', 'Clothing', 59.99, NOW()),
('Gap Slim Fit Shorts', 'Clothing', 34.99, NOW()),
('Vans Old Skool Sneakers', 'Clothing', 69.99, NOW()),
('Calvin Klein Boxer Briefs', 'Clothing', 39.99, NOW()),
('Patagonia Down Vest', 'Clothing', 229.99, NOW()),

-- Home & Kitchen (20 products)
('Instant Pot Duo 7-in-1', 'Home & Kitchen', 89.99, NOW()),
('Dyson V15 Vacuum', 'Home & Kitchen', 749.99, NOW()),
('KitchenAid Stand Mixer', 'Home & Kitchen', 449.99, NOW()),
('Ninja Air Fryer XL', 'Home & Kitchen', 119.99, NOW()),
('Nespresso Vertuo Coffee', 'Home & Kitchen', 179.99, NOW()),
('Cuisinart Food Processor', 'Home & Kitchen', 99.99, NOW()),
('Lodge Cast Iron Skillet', 'Home & Kitchen', 34.99, NOW()),
('Vitamix Blender 5200', 'Home & Kitchen', 549.99, NOW()),
('Roomba i7 Robot Vacuum', 'Home & Kitchen', 599.99, NOW()),
('Philips Air Purifier', 'Home & Kitchen', 249.99, NOW()),
('Keurig K-Elite Coffee', 'Home & Kitchen', 149.99, NOW()),
('Calphalon Cookware Set', 'Home & Kitchen', 299.99, NOW()),
('Breville Toaster Oven', 'Home & Kitchen', 199.99, NOW()),
('OXO Good Grips Set', 'Home & Kitchen', 49.99, NOW()),
('Pyrex Glass Storage Set', 'Home & Kitchen', 39.99, NOW()),
('Shark Steam Mop', 'Home & Kitchen', 79.99, NOW()),
('Bamboo Cutting Board Set', 'Home & Kitchen', 29.99, NOW()),
('Waterpik Water Flosser', 'Home & Kitchen', 69.99, NOW()),
('Honeywell Tower Fan', 'Home & Kitchen', 64.99, NOW()),
('Black+Decker Hand Mixer', 'Home & Kitchen', 24.99, NOW()),

-- Books (20 products)
('Clean Code - Robert Martin', 'Books', 34.99, NOW()),
('System Design Interview', 'Books', 39.99, NOW()),
('Spring Boot in Action', 'Books', 44.99, NOW()),
('Effective Java 3rd Edition', 'Books', 49.99, NOW()),
('Java Concurrency in Practice', 'Books', 44.99, NOW()),
('Designing Data-Intensive Apps', 'Books', 54.99, NOW()),
('The Pragmatic Programmer', 'Books', 39.99, NOW()),
('Head First Design Patterns', 'Books', 49.99, NOW()),
('Clean Architecture', 'Books', 34.99, NOW()),
('Microservices Patterns', 'Books', 44.99, NOW()),
('Docker Deep Dive', 'Books', 29.99, NOW()),
('Kubernetes in Action', 'Books', 54.99, NOW()),
('React Up and Running', 'Books', 34.99, NOW()),
('You Don''t Know JS', 'Books', 29.99, NOW()),
('The Linux Command Line', 'Books', 39.99, NOW()),
('Database Internals', 'Books', 49.99, NOW()),
('Grokking Algorithms', 'Books', 34.99, NOW()),
('Introduction to Algorithms', 'Books', 79.99, NOW()),
('Domain-Driven Design', 'Books', 54.99, NOW()),
('Building Microservices', 'Books', 49.99, NOW()),

-- Sports (20 products)
('Yoga Mat Premium', 'Sports', 29.99, NOW()),
('Resistance Bands Set', 'Sports', 19.99, NOW()),
('Adjustable Dumbbells 50lb', 'Sports', 299.99, NOW()),
('Pull-Up Bar Doorway', 'Sports', 34.99, NOW()),
('Jump Rope Speed Cable', 'Sports', 14.99, NOW()),
('Foam Roller Deep Tissue', 'Sports', 24.99, NOW()),
('Kettlebell 35lb', 'Sports', 49.99, NOW()),
('Wilson Tennis Racket', 'Sports', 89.99, NOW()),
('Spalding Basketball', 'Sports', 29.99, NOW()),
('Hydro Flask Water Bottle', 'Sports', 44.99, NOW()),
('Garmin Forerunner 255', 'Sports', 349.99, NOW()),
('Fitbit Charge 6', 'Sports', 159.99, NOW()),
('TRX Suspension Trainer', 'Sports', 149.99, NOW()),
('Bowflex Resistance Machine', 'Sports', 199.99, NOW()),
('Rollerblade Inline Skates', 'Sports', 119.99, NOW()),
('Callaway Golf Set', 'Sports', 499.99, NOW()),
('Speedo Swim Goggles', 'Sports', 19.99, NOW()),
('Camping Hiking Backpack', 'Sports', 89.99, NOW()),
('Boxing Gloves 16oz', 'Sports', 49.99, NOW()),
('Ab Roller Wheel Pro', 'Sports', 22.99, NOW());